config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
    registrations: 'users/registrations'
   } 
  root 'orders#index'
  resources :orders do
    collection { post :check }
    collection { get :history }
    collection { get :received }
    member { get :received_show }
    collection { get :search }
  end
  resources :users do
    collection { get :select }
  end
  resources :products do
    collection { post :import }
    member { get :detail }

  end

  resources :carts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_cart' => 'carts#my_cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  delete '/delete_item' => 'carts#delete_item'
  post '/add_regular' => 'carts#add_regular'
  post '/recall_regular' => 'carts#recall_regular'
  post '/delete_regular' => 'carts#delete_regular'

  resources :regulars
  resources :regular_products
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/regular.rb
class Regular < ApplicationRecord
    has_many :regular_products, dependent: :destroy
    belongs_to :user

    validates :regular_number, numericality: { in: 1..4 }
end

app/controllers/regulars_controller.rb
class RegularsController < ApplicationController
    before_action :set_regular, only: %i[ show edit update destroy ]
    def index

       @regulars = Regular.where(user_id: current_user.id).order(regular_number: "ASC")

      end

    def edit
      end

      def destroy
        @regular.destroy
    
        respond_to do |format|
          format.html { redirect_to regulars_url, notice: "リストは正常に削除されました。" }
          format.json { head :no_content }
        end
      end 

      def set_regular
        @regular = Regular.find(params[:id])
      end
end

app/helpers/regulars_helper.rb
module RegularsHelper
end

app/views/regulars/index.html.erb
<H3>「いつものあれ」リスト管理一覧</H3>

<% @regulars.each do |r| %>
    <div class="card">
<div class="card-body text-center">
<tr>    

  
    <td><%= r.regular_number %></td>番セット
   
    <td><%= link_to '削除', r, method: :delete, data: { confirm: '登録セットを削除しますか？' } %></td><br>
    <td><% r.regular_products.each do |rp| %>
        <%= rp.product.name %>
        <%= rp.regular_quantity %>個
        <td><%= link_to '個数変更', edit_regular_product_path(rp) %></td>
        <%= link_to '削除', rp, method: :delete, data: { confirm: '登録セット商品を削除しますか？' } %>
<br>
    <% end %></td>
</tr></div></div>
    <% end %>