config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
    registrations: 'users/registrations'
   } 
  root 'orders#index'
  resources :orders do
    collection { post :check }
    collection { get :history }
    collection { get :received }
    member { get :received_show }
    collection { get :search }
  end
  resources :users do
    collection { get :select }
  end
  resources :products do
    collection { post :import }
    member { get :detail }

  end

  resources :carts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_cart' => 'carts#my_cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  delete '/delete_item' => 'carts#delete_item'
  post '/add_regular' => 'carts#add_regular'
  post '/recall_regular' => 'carts#recall_regular'
  post '/delete_regular' => 'carts#delete_regular'

  resources :regulars
  resources :regular_products
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/order.rb
class Order < ApplicationRecord
    include Discard::Model
  
    has_many :cart_item, dependent: :destroy
    has_many :order_products
    belongs_to :user
    has_many :products, through: :order_products
    has_many :cart_items, through: :products

    
    enum status: { 発注済: 0, 店舗確認中: 1, 発送準備中: 2, 発送済: 3}
    
    
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ received_show show edit update destroy ]

  # GET /orders or /orders.json
  def index
   @q = Product.ransack(params[:q])
   @q.sorts = 'stock desc' if @q.sorts.empty?
   @products = @q.result.where(status: true, discarded_at: nil).page(params[:page]).per(20)
   @cart_items = current_cart.cart_items.includes([:product])
   @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
   @total_item = @cart_items.inject(0) { |sum, item| sum + item.quantity }
  

  
  end





  def history
    @q = Order.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @orders = @q.result.where(user_id: current_user.id, discarded_at: nil)
    

  end

  def received
    @q = Order.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @orders = @q.result.where(discarded_at: nil)
    
  
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_orders_csv(@orders)
      end
    end
    
    

  end

  def received_show
  
    @order_product = OrderProduct.where(order_id: params[:id])
  end


  # GET /orders/1 or /orders/1.json
  def show
    @order_product = OrderProduct.where(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
      cart_items = current_cart.cart_items.all
      @order = current_user.orders.new(order_params)
    begin
      ActiveRecord::Base.transaction do
        @order.save!
          cart_items.each do |cart|
            order_product = OrderProduct.new
            order_product.product_id = cart.product_id
            order_product.order_id = @order.id
            order_product.order_quantity = cart.quantity
            order_product.order_price = cart.product.price
            order_product.save!
            @product = Product.find(order_product.product_id)
            @product.stock -= order_product.order_quantity 
            @product.save!
          end
        redirect_to root_path
        flash[:notice] = '注文が送信されました。'
        cart_items.destroy_all
    end
    rescue
    flash[:notice] = 'カートに入っている商品の在庫数が足りません。申し訳ございませんが再度購入数をご確認いただけますと幸いです。'
    @order = Order.new(order_params)
      render :new
    end
  end
  


  
def check
  @order = Order.new(order_params)
  if params[:order][:address_number] == "1"
    @order.name = current_user.name 
    @order.address = current_user.company_address
  elsif params[:order][:address_number] == "2"
    if Address.exists?(name: params[:order][:registered])
      @order.name = Address.find(params[:order][:registered]).name
      @order.address = Address.find(params[:order][:registered]).address
    else
      render :new
    end
  elsif params[:order][:address_number] == "3"
    address_new = current_user.addresses.new(address_params)
    if address_new.save 
    else
      render :new
    end
  else
    redirect_to root_path 
  end
  @cart_items = current_cart.cart_items.all 
  @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params) && @order.status == "発送済"
        DeliveryMailer.with(order: @order, user: current_user).delivery_email.deliver_now
        format.html { redirect_to received_orders_path, notice: "受注情報が更新されました。" }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { redirect_to received_orders_path, notice: "受注情報が更新されました。" }
        format.json { render :show, status: :ok, location: @order }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.discard

    respond_to do |format|
      format.html { redirect_to received_orders_path, notice: "受注が削除されました。" }
      format.json { head :no_content }
    end
  end

  private

  
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
    params.require(:order).permit(:name, :address, :total_price, :status)
  end
  
  def address_params
    params.require(:order).permit(:name, :address)
  end

  def send_orders_csv(orders)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      column_names = %w(発注業者 発注日 発注時刻 配送先 合計金額 発送ステータス)
      csv << column_names
      orders.each do |order|
        column_values = [
          order.user.name,
          order.created_at.strftime("%-m月%-d日"),
          order.created_at.strftime("%-H時%-M分"),
          order.address,
          order.total_price.to_s(:delimited),
          order.status,
         
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "受注一覧.csv")
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_search.html.erb
<p>商品名でも商品説明でもキーワード一つで好きに検索できます！</p>
<%= search_form_for @q, url:orders_url do |f| %>
  <%= f.label :name, "キーワード" %>
  <%= f.search_field :name_or_description_cont %><br>

  <%= f.label :price %>
  <%= f.number_field :price_gteq %>以上〜
  <%= f.number_field :price_lt %>未満<br>
 
  <%= f.submit "検索" %>
<% end %><br>

app/views/orders/_status.html.erb
<%= form_with(model: order, local: true) do |form| %>
    <% if order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
  
        <ul>
          <% order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="status">
 <%= form.label :受注処理状況 %><br>
 <%= form.radio_button :status, '発注済' %>
 <%= form.label :status, '発注済', value: 0 %>

  <%= form.radio_button :status, '店舗確認中' %>
  <%= form.label :status, '店舗確認中', value: 1 %>

  <%= form.radio_button :status, '発送準備中' %>
  <%= form.label :status, '発送準備中', value: 2 %>

  <%= form.radio_button :status, '発送済' %>
  <%= form.label :status, '発送済', value: 3 %>
</div>  
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  







 

app/views/orders/check.html.erb
<H5>購入商品は以下の通りとなります。</H5>
<H5>よろしければ「注文を確定する」を押してください。</H5>

<H4><% @cart_items.each do |cart| %>
  <%= cart.product.name %>
  <%= (cart.product.price).to_s(:delimited) %>円
  <%= cart.quantity %>個
  小計<%= (cart.product.price*cart.quantity).to_s(:delimited) %>円<br>
<% end %></H4>
<br>
<H5>ご請求金額</H5>
<H4><%= @total.to_s(:delimited) %>円</H4>
<br>
<H5>お届け先</H5>
<H4><%= @order.name %><br>
<%= @order.address %></H4>


<%= form_with model: @order, url: orders_path(@order), local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :address %>
  <%= f.hidden_field :total_price, value: @total %>
  <%= f.submit "注文を確定する" %>
<% end %>
<%= button_to '戻る', :back, method: :get %>

app/views/orders/edit.html.erb
<h1>発送状況更新</h1>

<%= render 'status', order: @order %>


<%= link_to '受注一覧に戻る', received_orders_path %>

app/views/orders/history.html.erb
<H1>発注履歴</H1>
<p>発注ミス等がございましたら、すでに受注店舗様側にて配送が始まっている可能性がありますので直接受注店舗様にご連絡ください。受注店舗様にて発注取り消しが可能です。</p>
<div class="row">
<div class="col-12 d-flex justify-content-center">

<table>
  <thead>
    <tr>
    <th> <%= sort_link(@q, :created_at, "発注日") %></th>
    <th>時間</th>
    <th> <%= sort_link(@q, :status, "ステータス") %></th>
    <th>配送先</th>
    <th>合計金額</th>
    <th>発注詳細</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
      <td><%= order.created_at.strftime("%Y年%-m月%-d日") %></td>
      <td><%= order.created_at.strftime("%-H時%-M分") %></td>
      <td><%= order.status %></td>
      <td><%= order.address %></td>

      <td><%= order.total_price.to_s(:delimited) %>円</td>

        <td><%= link_to '発注詳細', order %></td>
  

      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/orders/index.html.erb
<H3> NOKIA NET SHOP </H3>

<%= render 'search' %>
<%= paginate @products %>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3">
         
      <div class="card">
          <div class="card-body text-center">
           <tr>
              <td>
              <% if product.image.blank? %>
              <%= link_to image_tag('noimage.png', size: '120x120', alt: "サンプル画像"), product_path(product) %>
              <% else %>
              <%= link_to image_tag(product.image.url, size: '120x120', alt: "商品画像"), product_path(product) %>
              <% end %>
              </td><br>
              <td><%= product.name.truncate(15) %></td><br>
              <td><%= product&.description&.truncate(15) %></td><br>
              <td><%= product.price.to_s(:delimited) %></td>円(税込)<br>
              <td>残り<%= product.stock %></td>個<br>
              
              <td>
              <% if product.stock > 0 %>
              <%= form_with url: add_item_path do |form| %>
                <%= form.hidden_field :product_id, value: product.id %>
                <%= form.number_field :quantity, autofocus: true, autocomplete: "quantity", value: 1, min: 1, max:product.stock %>
                <%= form.submit("商品をかごに追加") %>
              <% end %>
               
               
              <% else %>
                <%= button_to '在庫なし', add_item_path(product_id: product, quantity: 1), class: 'fbtn', disabled: true %>
              <% end %>
             </td>
            </tr>
            </div>
            </div>
       </div>
        
    <% end %>
  </div>



   
<br>



<%= render partial: "carts/cart" %>

app/views/orders/new.html.erb
<h1>配送先確認</h1>



<!-- @order でラジオボタンを使って情報を送ります -->
<%= form_with model: @order, url: check_orders_path, local: true do |f| %>
<!-- customer テーブルに登録されている住所の場合です -->
  <%= f.radio_button :address_number, 1, checked: true %> <!-- address_number と定義して1～3の番号を check に送ります -->
  <%= f.label :address_number_1, "登録住所" %><%= current_user.company_address %><br>



  <!-- 新しい住所を追加する場合です -->
  <%= f.radio_button :address_number, 3 %>
  <%= f.label :address_number_3, "登録住所以外のお届け先" %>
  <%= f.label :name, "宛先" %>
  <%= f.text_field :name %>
  <%= f.label :address, "住所" %>
  <%= f.text_field :address %>
  
<!-- 選んでもらったデータを送ります -->
<br>
  <%= f.submit "確認画面へ進む" %>
<% end %>
<%= button_to '戻る', :back, method: :get %>

app/views/orders/received.html.erb
<H1>受注履歴</H1>



<%= link_to 'CSV形式でダウンロードする', received_orders_path(format: :csv) %>
<div class="row">
  <div class="col-12 d-flex justify-content-center">

<table>
  <thead>
    <tr>
    <th> <%= sort_link(@q, :created_at, "発注日") %></th>
    <th>時間</th>
    <th> <%= sort_link(@q, :status, "ステータス") %></th>
    <th>発注業者</th>
    <th>配送先</th>
    <th>合計金額</th>
    <th>商品</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      
      <tr> 
          <td><%= order.created_at.strftime("%Y年%-m月%-d日") %></td>
          <td><%= order.created_at.strftime("%-H時%-M分") %></td>
          <td><%= order.status %></td>
          <td><%= order&.user&.name %></td>
          <td><%= order&.address %></td>
          <td><%= order&.total_price&.to_s(:delimited) %>円</td>
          <td>
          <% order.order_products.each do |op| %>
            <%= op.product.name %>
            <%= op.order_quantity %>個<br>
          <% end %>
          </td>
          <td><%= link_to '詳細確認', received_show_order_path(order) %></td>
          <td><%= link_to '編集', edit_order_path(order) %></td>
          <td><%= link_to '受注削除', order, method: :delete, data: { confirm: '受注を削除します。先方の発注業者様の確認は取れておりますでしょうか?' } %></td>
       </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/orders/received_show.html.erb
<H4>受注詳細</H4>

発注日:<%= @order.created_at.strftime("%Y年%-m月%-d日") %><br>
時間:<%= @order.created_at.strftime("%-H時%-M分") %><br>
配送先:<%= @order.address %><br>
支払総額:<%= @order.total_price.to_s(:delimited) %>円<br>
発送状況:<%= @order.status %><br>

商品詳細:<% @order_product.each do |order_product| %>
    <%= order_product&.product&.name %>
    <%= (order_product.product.price).to_s(:delimited) %>円
    <%= order_product&.order_quantity %>個
    小計<%= (order_product&.product&.price*order_product.order_quantity).to_s(:delimited) %>円<br>
  <% end %>



<%= link_to '戻る', received_orders_path %>

app/views/orders/show.html.erb
<H4>発注詳細</H4>

発注日:<%= @order.created_at.strftime("%Y年%-m月%-d日") %><br>
時間:<%= @order.created_at.strftime("%-H時%-M分") %><br>
配送先:<%= @order.address %><br>
支払総額:<%= @order.total_price.to_s(:delimited) %>円<br>
発送状況:<%= @order.status %><br>

商品詳細:<% @order_product.each do |order_product| %>
    <%= order_product&.product&.name %>
    <%= (order_product.product.price).to_s(:delimited) %>円
    <%= order_product&.order_quantity %>個
    小計<%= (order_product&.product&.price*order_product.order_quantity).to_s(:delimited) %>円<br>
  <% end %>



<%= link_to '戻る', history_orders_path %>