config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
    registrations: 'users/registrations'
   } 
  root 'orders#index'
  resources :orders do
    collection { post :check }
    collection { get :history }
    collection { get :received }
    member { get :received_show }
    collection { get :search }
  end
  resources :users do
    collection { get :select }
  end
  resources :products do
    collection { post :import }
    member { get :detail }

  end

  resources :carts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_cart' => 'carts#my_cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  delete '/delete_item' => 'carts#delete_item'
  post '/add_regular' => 'carts#add_regular'
  post '/recall_regular' => 'carts#recall_regular'
  post '/delete_regular' => 'carts#delete_regular'

  resources :regulars
  resources :regular_products
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :setup_cart_item!, only: %i[ add_item update_item delete_item]

    # カート内アイテムの表示
    def my_cart
      @cart_items = current_cart.cart_items.includes([:product])
      @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
      @total_item = @cart_items.inject(0) { |sum, item| sum + item.quantity }
      @regulars = Regular.where(user_id: current_user.id)
    end
  
    # アイテムの追加
    def add_item
      @cart_item ||= current_cart.cart_items.build(product_id: params[:product_id])
      @cart_item.quantity += params[:quantity].to_i
      if  @cart_item.save
        flash[:notice] = '商品が追加されました。'
        redirect_to root_path
      else
        flash[:alert] = '商品の追加に失敗しました。'
        redirect_to product_url(params[:product_id])
      end
    end

    def add_regular
      @regular = Regular.find_or_initialize_by(user_id: current_user.id, regular_number: params[:regular_number])
      @regular.save
      regular_product = RegularProduct.find_or_initialize_by(regular_id: @regular.id, product_id: params[:product_id])
      regular_product.product_id = params[:product_id]
      regular_product.regular_quantity = params[:regular_quantity]
      regular_product.regular_id = @regular.id
      regular_product.save!     
      if  @regular.save
        flash[:notice] = '商品が"いつものあれ"リストに追加されました。「管理」⇒「いつものあれリスト」からも確認できます。'
        redirect_to product_url(params[:product_id])
      else
        flash[:alert] = '"いつものあれ"リストへの追加に失敗しました。'
        redirect_to product_url(params[:product_id])
      end
    end

    def recall_regular
      @regular = Regular.find_by(user_id: current_user.id, regular_number: params[:regular_number])
      @r = RegularProduct.where(regular_id: @regular)
      begin
        ActiveRecord::Base.transaction do
          @r.each do |r|
          @cart_item = current_cart.cart_items.find_or_initialize_by(product_id: r.product_id)
          @cart_item.quantity += r.regular_quantity.to_i
          @cart_item.cart_id ||= Cart.find(user_id: current_user.id) 
          @product = Product.find_by(id: r.product_id)
            if @cart_item.quantity <= @product.stock
          @cart_item.save!
            else
          raise 
          end
        end
        flash[:notice] = '"いつものあれ"リストから呼び出されました。'
        redirect_to my_cart_path
        end
        rescue
        flash[:alert] = '在庫数が不足しており"いつものあれ"リストの商品を必要数カートに入れることができませんでした。'
        redirect_to my_cart_path
      end
    end
  
    # アイテムの更新
    def update_item
      if @cart_item.update(quantity: params[:quantity].to_i)
        flash[:notice] = 'カート内のアイテムが更新されました。'
      else
        flash[:alert] = 'カート内のアイテムの更新に失敗しました。'
      end
      redirect_to my_cart_path
    end
  
    # アイテムの削除
    def delete_item
      if @cart_item.destroy
        flash[:notice] = 'カート内のアイテムが削除されました。'
      else
        flash[:alert] = '削除に失敗しました。'
      end
      redirect_to my_cart_path
    end

    def delete_regular
      @regulars = Regular.find_by(user_id: current_user.id, product_id: params[:product_id])
      if @regulars.destroy
        flash[:notice] = '"いつものあれ"リストから正常に削除されました。'
      else
        flash[:alert] = '"いつものあれ"リストからの削除に失敗しました。'
      end
      redirect_to product_url(params[:product_id])
    end
  
    private
  
    def setup_cart_item!
      @cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
    end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart">
<div class="wrapper">

 <H3><%= "商品数: #{@total_item}点" %></H3>
 <H3><%= "合計：#{@total&.to_s(:delimited)}円" %></H3>


<div class="logo">
<%= link_to (image_tag "cart.png", height: "55", with: "70", class: "btn"), my_cart_path %>
<%= link_to "買い物かご確認", my_cart_path %>
 </div>

 </div>
</div>

app/views/carts/_cart_item.html.erb
<div class="card">
<div class="card-body text-center">

<li class="list-none">
<% if cart_item.product.image.blank? %>
       <%= image_tag 'noimage.png', :size => '120x120' %>
       <% else %>
       <%= image_tag cart_item.product.image.url, :size => '120x120' %>
       <% end %>
    <%= cart_item.product.name %>
    <%= cart_item.product.price&.to_s(:delimited) %>円
    残り<%= cart_item.product.stock&.to_s(:delimited) %>個
    <%= form_with(url: update_item_url, method: :post, local: true) do |f| %>
    <%= f.hidden_field :product_id, value: cart_item.product.id %>
    <%= f.number_field :quantity ,value: cart_item.quantity, min: 1, max: cart_item.product.stock %>個
    <%= f.submit "更新", class: "" %>
    <% end %>
    <%= button_to "削除", delete_item_path(product_id: cart_item.product.id), method: :delete,
                                       data: { confirm: "カートから商品を削除しますか？" } %>
</li>
</div>
</div>

app/views/carts/my_cart.html.erb
<h2>カート内アイテム</h2>
<%= render partial: "carts/cart_item", collection: @cart_items, as: "cart_item"%>
<h2><%= "合計：#{@total&.to_s(:delimited)}円" %></h2>

<% if @total == 0 %>
<%= link_to '商品を選んでください', orders_path %>
<% else %>
<%= button_to '購入に進む', new_order_path, method: :get %>
<% end %>
<br>

<%= form_with url: recall_regular_path do |form| %>
    リスト番号<%= form.number_field :regular_number, autofocus: true, autocomplete: "regular_number", value: 1, min: 1, max: 4 %>番<br>
    <%= form.submit("「いつものあれ」リストをカートに入れる。") %>
   <% end %>