config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
    registrations: 'users/registrations'
   } 
  root 'orders#index'
  resources :orders do
    collection { post :check }
    collection { get :history }
    collection { get :received }
    member { get :received_show }
    collection { get :search }
  end
  resources :users do
    collection { get :select }
  end
  resources :products do
    collection { post :import }
    member { get :detail }

  end

  resources :carts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_cart' => 'carts#my_cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  delete '/delete_item' => 'carts#delete_item'
  post '/add_regular' => 'carts#add_regular'
  post '/recall_regular' => 'carts#recall_regular'
  post '/delete_regular' => 'carts#delete_regular'

  resources :regulars
  resources :regular_products
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  validates :name, uniqueness: { scope: [:discarded_at, :user] }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :stock, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, in: 1..999 }

    has_many :cart_items, dependent: :destroy
    has_many :order_products, dependent: :destroy
    has_many :orders, through: :order_products
    belongs_to :user
    has_many :regular_products, dependent: :destroy
    enum status: { 出品中: true, 取り下げ中: false }
    mount_uploader :image, ImageUploader

  #エラーチェック処理
    def self.csv_format_check(file)
      errors = []
    CSV.foreach(file.path, headers: true).with_index(2) do |row, index|
      product = new(name: row[0], stock: row["在庫数"], price: row["税込価格"], description: row["商品説明"])
      if row[0].present?
        errors << "#{index}行目 商品名が空白です" if product.name.blank?
        errors << "#{index}行目 税込価格が空白です" if product.price.blank?
      else
        errors << "#{index}行目 商品名が空白です" if product.name.blank?
      end
      if row["在庫数"].present?
        errors << "#{index}行目 在庫数が無効です" if product.stock > 999
      else
        errors << "#{index}行目 在庫数が空白です" if product.stock.blank?
      end
      

    end
    errors
  end
      

  #登録処理
      def self.import_save(file, current)
        new_count = 0
        update_count = 0
        nochange_count = 0
        failure = 0
        failures = []
        CSV.foreach(file.path, headers: true).with_index(2) do |row, index|
          if product = find_by(name: row[0], user_id: current, discarded_at: nil)
            product.assign_attributes(name: row[0], stock: row["在庫数"], price: row["税込価格"], description: row["商品説明"])
            if product.changed?
              if product.save
                update_count += 1
              else
                failure += 1
                failures << "#{index}行目"
              end
            else
              nochange_count += 1
            end
          else
            product = new(name: row[0], stock: row["在庫数"], price: row["税込価格"], description: row["商品説明"], user_id: current)
              if product.save
              new_count += 1
              else
              failure += 1
              failures << "#{index}行目"
              end
          end
        end
        "新規登録：#{new_count}件、更新：#{update_count}件、変更なし：#{nochange_count}件、更新失敗：#{failure}件#{failures}"
      end
      
      def self.updatable_attributes
        ["name", "description", "price", "stock"]
      end

      CSV_HEADER = {
        '商品名' => 'name',   
        '商品説明' => 'description', 
        '税込価格' => 'price',  
        '在庫数' => 'stock'
      }.freeze

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ detail show edit update destroy ]

  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @q.sorts = 'updated_at desc' if @q.sorts.empty?
    @products = @q.result.where(user_id: current_user.id, discarded_at: nil)

    
  end

  

  def import
    if params[:file].present?
      if Product.csv_format_check(params[:file]).present?
        redirect_to products_path, notice: "エラーが発生したため処理を中断しました。#{Product.csv_format_check(params[:file])}"
      else
        message = Product.import_save(params[:file], current_user.id)
        redirect_to products_path, notice: "インポート商品登録が完了しました。#{message}"
      end
    else
      redirect_to products_path, notice: "インポート処理が失敗しました。ファイルを選択し直してください。"
    end
  end

  

  # GET /products/1 or /products/1.json
  def show
    @regular = Regular.where(user_id: current_user.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def detail
  end



  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: "商品登録が完了しました。" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: "商品情報が正常に更新されました。" }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.discard

    respond_to do |format|
      format.html { redirect_to products_url, notice: "商品は正常に削除されました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(
      :name, 
      :price, 
      :stock, 
      :status,
      :description,
      :image,
      images_attributes: [:src]
      )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= form.label :price %><br/>(税込価格で登録してください。)<br />
    <%= form.number_field :price, autofocus: true, autocomplete: "price" %>
  </div>

  <div class="field">
    <%= form.label :stock %><br />
    <%= form.number_field :stock, autofocus: true, autocomplete: "stock" %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description, autofocus: true, autocomplete: "description" %>
  </div>

  <div class="field">
    <%= form.label :image %>(一枚まで)<br />
    <%= form.file_field :image, autofocus: true, autocomplete: "image" %>
  </div>
  
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_form2.html.erb
<%= form_with(model: @product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
  
        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %><br />
      <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>
  
    <div class="field">
      <%= form.label :price %><br />
      <%= form.number_field :price, autofocus: true, autocomplete: "price" %>
    </div>
  
    <div class="field">
      <%= form.label :stock %><br />
      <%= form.number_field :stock, autofocus: true, autocomplete: "stock" %>
    </div>

    <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description, autofocus: true, autocomplete: "description" %>
  </div>


    <div class="field">
  <%= form.label :出品状況 %>
  <%= form.radio_button :status, '出品中' %>
  <%= form.label :status, '出品中', value: true %>

   <%= form.radio_button :status, '取り下げ中' %>
   <%= form.label :status, '取り下げ中', value: false %>
   </div>

   <div class="field">
   <%= form.label :image %><br />
   <%= form.file_field :image, autofocus: true, autocomplete: "image" %>
 </div>
 <br>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/products/detail.html.erb
<p>商品画像: </p>
<% if @product.image.blank? %>
       <%= image_tag 'noimage.png', :size => '150x150' %>
       <% else %>
       <%= image_tag @product.image.url, :size => '150x150' %>
       <% end %>
<H5>名前: <%= @product.name %></H5>
<H5>金額: <%= @product.price.to_s(:delimited) %>円</H5>
<H5>商品説明: <%= @product.description %></H5>
<H5>在庫: 残り<%= @product.stock %>個</H5>



<%= link_to "戻る", products_path %>
<br>

app/views/products/edit.html.erb
<h1>商品情報編集</h1>
<%= render 'form2', product: @product %>

 

<%= link_to 'Back', products_path %>


 

app/views/products/index.html.erb
<h1>商品管理</h1>

<%= link_to '一つずつ商品を登録する', new_product_path %>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "CSVで商品を一括登録する" %>
<% end %>
<div class="row">
<div class="col-12 d-flex justify-content-center">

<table>
  <thead>
    <tr>
    <th>商品画像</th>
    <th> <%= sort_link(@q, :name, "商品名") %></th>
    <th> <%= sort_link(@q, :price, "価格") %></th>
    <th> <%= sort_link(@q, :stock, "在庫数") %></th>
    <th>商品説明</th>
    <th> <%= sort_link(@q, :status, "出品状況") %></th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <td><% if product.image.blank? %>
       <%= image_tag 'noimage.png', :size => '30x30' %>
       <% else %>
       <%= image_tag product.image.url, :size => '30x30' %>
       <% end %></td>
      <td><%= product.name.truncate(20)  %></td>
      <td><%= product.price.to_s(:delimited) %>円</td>
      <td><%= product.stock.to_s(:delimited) %>個</td>
      <td><%= product&.description&.truncate(40) %></td>
      <td><%= product.status %></td>
        <td><%= link_to '詳細', detail_product_path(product) %></td>
        <td><%= link_to '編集', edit_product_path(product) %></td>
        <td><%= link_to '削除', product, method: :delete, data: { confirm: '出品を取りやめるだけなら編集⇒取り下げからも対応可能となっております。それでも商品を削除いたしますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
</div>

app/views/products/new.html.erb
<h1>商品登録</h1>

<%= render 'form', product: @product %>

<%= link_to '戻る', products_path %>

app/views/products/show.html.erb
<p>商品画像: </p>
<% if @product.image.blank? %>
       <%= image_tag 'noimage.png', :size => '150x150' %>
       <% else %>
       <%= image_tag @product.image.url, :size => '150x150' %>
       <% end %>
<H5>名前: <%= @product.name %></H5>
<H5>金額: <%= @product.price.to_s(:delimited) %>円</H5>
<H5>商品説明: <%= @product.description %></H5>
<H5>在庫: 残り<%= @product.stock %>個</H5>



<%= link_to "トップページ", root_path %>


 <%= form_with url: add_regular_path do |form| %>
  <%= form.hidden_field :product_id, value: @product.id %>
  リスト番号<%= form.number_field :regular_number, autofocus: true, autocomplete: "regular_number", value: 1, min: 1, max: 4 %>番(4セットまで登録できます。)<br>
  <%= form.number_field :regular_quantity, autofocus: true, autocomplete: "regular_quantity", value: 1, min: 1, max: 999 %>個
  <%= form.submit("商品を「いつものあれ」リストに追加") %>
 <% end %>
               
       


<br>